apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.microservice.test
      http:
        paths:
          - backend:
              service:
                name: posts-clusterip-svc
                port:
                  number: 4000
            path: /posts
            pathType: Exact
